# if you use this PVC
# switch out the emptyDir in deployment.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-cobol
  labels:
    billingType: "monthly"
    region: us-south
    zone: dal10
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 24Gi
  storageClassName: ibmc-file-silver
